apiVersion: v1
kind: Service
metadata:
  name: bank-account-service
  labels:
    app: bank-account
    tier: backend
    component: service
spec:
  type: ClusterIP
  selector:
    app: bank-account
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
